# Generated by Django 5.2.7 on 2026-05-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('RETRYING', 'Retrying')], default='RUNNING', max_length=16)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'event_sync_job',
            },
        ),
    ]
