# Generated by Django 5.2.7 on 2026-05-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0036_fights_url'),
        ('ufc_data_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsyncjob',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('RETRYING', 'Retrying'), ('FAILED', 'Failed')], default='RUNNING', max_length=16),
        ),
        migrations.CreateModel(
            name='FightCreationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('RETRYING', 'Retrying'), ('FAILED', 'Failed')], default='RUNNING', max_length=16)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('pubsub_message_id', models.CharField(blank=True, help_text='GCP Pub/Sub message_id so redeliveries update the same row.', max_length=256, null=True, unique=True)),
                ('url', models.CharField(max_length=512)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fight_creation_jobs', to='fantasy.events')),
            ],
            options={
                'db_table': 'fight_creation_job',
            },
        ),
    ]
