# Generated by Django 5.2.7 on 2026-07-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_data_pipeline', '0006_career_stats_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreFightJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('RETRYING', 'Retrying'), ('FAILED', 'Failed')], default='RUNNING', max_length=16)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('fight_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'score_fight_job',
            },
        ),
        migrations.AddIndex(
            model_name='scorefightjob',
            index=models.Index(fields=['fight_id', 'status'], name='score_fight_fight_i_f0cbdf_idx'),
        ),
    ]
