# Generated by Django 5.x for Pub/Sub job dedupe fields and active-job constraints.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ufc_data_pipeline", "0010_live_event_rescrape_handoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerstatsjob",
            name="pubsub_message_id",
            field=models.CharField(
                blank=True,
                help_text="GCP Pub/Sub message_id so redeliveries map to one job row.",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="fighterprofilescrapejob",
            name="pubsub_message_id",
            field=models.CharField(
                blank=True,
                help_text="GCP Pub/Sub message_id so redeliveries map to one job row.",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="fightstatsscrapejob",
            name="pubsub_message_id",
            field=models.CharField(
                blank=True,
                help_text="GCP Pub/Sub message_id so redeliveries map to one job row.",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="scorefightjob",
            name="pubsub_message_id",
            field=models.CharField(
                blank=True,
                help_text="GCP Pub/Sub message_id so redeliveries map to one job row.",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="careerstatsjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "RUNNING", "RETRYING"])),
                fields=("fight_id",),
                name="uniq_career_stats_active_fight",
            ),
        ),
        migrations.AddConstraint(
            model_name="fightcreationjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "RUNNING", "RETRYING"])),
                fields=("event_id",),
                name="uniq_fight_creation_active_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="fighterprofilescrapejob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "RUNNING", "RETRYING"])),
                fields=("fighter_id",),
                name="uniq_fighter_profile_active_fighter",
            ),
        ),
        migrations.AddConstraint(
            model_name="fightstatsscrapejob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "RUNNING", "RETRYING"])),
                fields=("fight_id",),
                name="uniq_fight_stats_active_fight",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorefightjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "RUNNING", "RETRYING"])),
                fields=("fight_id",),
                name="uniq_score_fight_active_fight",
            ),
        ),
    ]
