from django.urls import path, include
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('fighters/', views.GetFighterProfileViewSet.as_view()),
    path('events', views.GetEventViewSet),
    path('fights', views.GetFightViewSet),
    path('fighter/<int:id>', views.GetCareerStatsViewSet),
    path('fights/<int:id>', views.GetFighterFightsViewSet),
    path('fights/<int:id>/fantasy-scores/recent', views.GetLastFiveFantasyScoresViewSet),
    path('events/<int:id>', views.GetFightsFromEventViewSet),
    path('fight/<int:id>', views.GetHeadToHeadStatsViewSet),
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('create-league', views.CreateLeague),
    path('leagues', views.GetUserLeaguesAndTeams.as_view()),
    path('league/<int:league_id>', views.GetLeagueData),
    path('league/<league_id>/draft/schedule', views.SetDraftDate),
    path('league/join', views.CreateLeagueMember),
    path('team/<int:team_id>', views.GetTeamListData),
    path('api/team/<int:team_id>/changeName', views.ChangeTeamName),
    path('draft/<int:draft_id>/state', views.GetDraftState),
    path('draft/<int:draft_id>/draftableFighters', views.GetDraftableFighters.as_view()),
    path('draft/<int:draft_id>/pastPicks', views.GetDraftPickHistory),
    path('draft/<int:draft_id>/pick', views.AddRosterSlot),
    path('draft/<int:draft_id>/draftFlex', views.DraftFlexSlot),
    path('draft/<int:draft_id>/draftOrder', views.GetDraftOrder),
    path('api/me', views.GetCurrentUserViewSet),
    path('api/setUserName', views.SetUsername),
    path('api/previewLeague', views.PreviewLeagueByJoinKey),
    path('api/<int:team_id>/SetTeamImage', views.SetTeamImage.as_view()),
    path('api/fighters/ImageCandidates', views.GetFighterImageCandidates.as_view()),
    path('api/fighters/<int:fighter_id>/SetFighterImage', views.AddFighterImageURL.as_view()),
    path('api/fighters/<int:fighter_id>/SetFighterProfile', views.SetFighterProfile.as_view()),
    path('api/fights/<int:fight_id>/SetFightResultMetadata', views.SetFightResultMetadata.as_view()),
    path('api/fights/<int:fight_id>/SetFightStatsTotals', views.SetFightStatsTotals.as_view()),
    path('api/fights/<int:fight_id>/SetRoundStats', views.SetRoundStats.as_view()),
    path('api/fights/<int:fight_id>/CareerStatsSource', views.CareerStatsSource.as_view()),
]