services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - .env

  scraper-job:
    build:
      context: ./backend
      dockerfile: athlete_image_service/Dockerfile
    env_file:
      - .env
    depends_on:
      - web
      - pubsub

  image-worker-job:
    build:
      context: ./backend
      dockerfile: image_worker_service/Dockerfile
    env_file:
      - .env
    depends_on:
      - web
      - pubsub
  
  pubsub:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
    environment:
      - PUBSUB_PROJECT_ID=local-project

  pubsub-init:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    depends_on:
      - pubsub
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - GOOGLE_CLOUD_PROJECT=local-project
      - CLOUDSDK_API_ENDPOINT_OVERRIDES_PUBSUB=http://pubsub:8085/
    command: >
      sh -c "
      sleep 5 &&
      gcloud config set auth/disable_credentials true &&
      gcloud config set project local-project &&
      gcloud pubsub topics create image-jobs --project=local-project &&
      gcloud pubsub subscriptions create image-worker-sub --topic=image-jobs --project=local-project
      "

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    command: celery -A ufc_fantasy worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      