# Generated by Django 5.2.7 on 2025-10-13 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fighters',
            fields=[
                ('fighter_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nick_name', models.CharField(max_length=50)),
                ('stance', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('reach', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FighterCareerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fights', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('knockouts', models.IntegerField(default=0)),
                ('submissions', models.IntegerField(default=0)),
                ('unanimous_decisions', models.IntegerField(default=0)),
                ('split_decisions', models.IntegerField(default=0)),
                ('sig_str_landed', models.IntegerField(default=0)),
                ('sig_str_attempted', models.IntegerField(default=0)),
                ('total_str_landed', models.IntegerField(default=0)),
                ('total_str_attempted', models.IntegerField(default=0)),
                ('td_landed', models.IntegerField(default=0)),
                ('td_attempted', models.IntegerField(default=0)),
                ('sub_att', models.IntegerField(default=0)),
                ('ctrl_time', models.IntegerField(default=0)),
                ('reversals', models.IntegerField(default=0)),
                ('head_strikes', models.IntegerField(default=0)),
                ('body_strikes', models.IntegerField(default=0)),
                ('leg_strikes', models.IntegerField(default=0)),
                ('distance_strikes', models.IntegerField(default=0)),
                ('clinch_strikes', models.IntegerField(default=0)),
                ('ground_strikes', models.IntegerField(default=0)),
                ('fighter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fantasy.fighters')),
            ],
        ),
        migrations.CreateModel(
            name='Fights',
            fields=[
                ('fight_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_class', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
                ('round', models.IntegerField()),
                ('round_format', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.events')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasy.fighters')),
            ],
        ),
        migrations.CreateModel(
            name='FightStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=10)),
                ('kd', models.IntegerField(default=0)),
                ('sig_str_landed', models.IntegerField(default=0)),
                ('sig_str_attempted', models.IntegerField(default=0)),
                ('total_str_landed', models.IntegerField(default=0)),
                ('total_str_attempted', models.IntegerField(default=0)),
                ('td_landed', models.IntegerField(default=0)),
                ('td_attempted', models.IntegerField(default=0)),
                ('sub_att', models.IntegerField(default=0)),
                ('ctrl_time', models.IntegerField(default=0)),
                ('reversals', models.IntegerField(default=0)),
                ('head_strikes', models.IntegerField(default=0)),
                ('body_strikes', models.IntegerField(default=0)),
                ('leg_strikes', models.IntegerField(default=0)),
                ('distance_strikes', models.IntegerField(default=0)),
                ('clinch_strikes', models.IntegerField(default=0)),
                ('ground_strikes', models.IntegerField(default=0)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.fights')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.fighters')),
            ],
        ),
        migrations.CreateModel(
            name='RoundStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('kd', models.IntegerField(default=0)),
                ('sig_str_landed', models.IntegerField(default=0)),
                ('sig_str_attempted', models.IntegerField(default=0)),
                ('total_str_landed', models.IntegerField(default=0)),
                ('total_str_attempted', models.IntegerField(default=0)),
                ('td_landed', models.IntegerField(default=0)),
                ('td_attempted', models.IntegerField(default=0)),
                ('sub_att', models.IntegerField(default=0)),
                ('ctrl_time', models.IntegerField(default=0)),
                ('reversals', models.IntegerField(default=0)),
                ('head_strikes', models.IntegerField(default=0)),
                ('body_strikes', models.IntegerField(default=0)),
                ('leg_strikes', models.IntegerField(default=0)),
                ('distance_strikes', models.IntegerField(default=0)),
                ('clinch_strikes', models.IntegerField(default=0)),
                ('ground_strikes', models.IntegerField(default=0)),
                ('fight_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.fightstats')),
            ],
        ),
    ]
