# Generated by Django 5.2.7 on 2025-10-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighters',
            name='height',
            field=models.IntegerField(null=True),
        ),
    ]
