# Generated by Django 5.2.7 on 2025-10-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_fighters_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightstats',
            name='body_strikes',
        ),
        migrations.RemoveField(
            model_name='fightstats',
            name='clinch_strikes',
        ),
        migrations.RemoveField(
            model_name='fightstats',
            name='distance_strikes',
        ),
        migrations.RemoveField(
            model_name='fightstats',
            name='ground_strikes',
        ),
        migrations.RemoveField(
            model_name='fightstats',
            name='head_strikes',
        ),
        migrations.RemoveField(
            model_name='fightstats',
            name='leg_strikes',
        ),
        migrations.AddField(
            model_name='fightstats',
            name='body_strikes_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='body_strikes_landed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='clinch_strikes_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='clinch_strikes_landed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='distance_strikes_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='distance_strikes_landed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='ground_strikes_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='ground_strikes_landed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='head_strikes_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='head_strikes_landed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='leg_strikes_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='leg_strikes_landed',
            field=models.IntegerField(default=0),
        ),
    ]
