# Generated by Django 5.2.7 on 2025-11-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0006_alter_fightstats_body_str_attempted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
