# Generated by Django 5.2.7 on 2025-11-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0007_alter_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='fights',
            name='bout',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
