# Generated by Django 5.2.7 on 2025-11-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0008_fights_bout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fights',
            name='weight_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
