# Generated by Django 5.2.7 on 2025-11-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0009_alter_fights_weight_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightstats',
            name='bout',
        ),
    ]
