# Generated by Django 5.2.7 on 2025-11-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0010_remove_fightstats_bout'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighters',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
