# Generated by Django 5.2.7 on 2025-11-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0011_fighters_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightercareerstats',
            name='knockouts',
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='dq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='ko_tko',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='majority_decisions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='tko_doctor_stoppage',
            field=models.IntegerField(default=0),
        ),
    ]
