# Generated by Django 5.2.7 on 2025-11-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0012_remove_fightercareerstats_knockouts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightercareerstats',
            name='tko_doctor_stoppage',
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='tko_doctor_stoppages',
            field=models.IntegerField(default=0),
        ),
    ]
