# Generated by Django 5.2.7 on 2025-11-14 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0013_remove_fightercareerstats_tko_doctor_stoppage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_win', models.FloatField(blank=True, default=0, null=True)),
                ('points_round', models.FloatField(blank=True, default=0, null=True)),
                ('points_time', models.FloatField(blank=True, default=0, null=True)),
                ('fight_total_points', models.FloatField(blank=True, default=0, null=True)),
                ('fight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.fights')),
                ('fighter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.fighters')),
            ],
        ),
        migrations.CreateModel(
            name='RoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_knockdowns', models.FloatField(blank=True, default=0, null=True)),
                ('points_sig_str_landed', models.FloatField(blank=True, default=0, null=True)),
                ('points_sig_str_attempted', models.FloatField(blank=True, default=0, null=True)),
                ('points_td_landed', models.FloatField(blank=True, default=0, null=True)),
                ('points_td_attempted', models.FloatField(blank=True, default=0, null=True)),
                ('points_sub_att', models.FloatField(blank=True, default=0, null=True)),
                ('points_ctrl_time', models.FloatField(blank=True, default=0, null=True)),
                ('points_reversals', models.FloatField(blank=True, default=0, null=True)),
                ('round_total_points', models.FloatField(blank=True, default=0, null=True)),
                ('round_stats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.roundstats')),
            ],
        ),
    ]
