# Generated by Django 5.2.7 on 2025-11-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0014_fightscore_roundscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundscore',
            name='points_sig_str_attempted',
        ),
        migrations.RemoveField(
            model_name='roundscore',
            name='points_td_attempted',
        ),
    ]
