# Generated by Django 5.2.7 on 2025-11-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0015_remove_roundscore_points_sig_str_attempted_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fightscore',
            constraint=models.UniqueConstraint(fields=('fight', 'fighter'), name='unique_fight_fighter_per_fight'),
        ),
        migrations.AddConstraint(
            model_name='roundscore',
            constraint=models.UniqueConstraint(fields=('round_stats',), name='unique_roundscore_per_round'),
        ),
    ]
