# Generated by Django 5.2.7 on 2025-11-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0016_fightscore_unique_fight_fighter_per_fight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fights',
            name='time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
