# Generated by Django 5.2.7 on 2025-12-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0017_alter_fights_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightercareerstats',
            name='dq',
        ),
        migrations.RemoveField(
            model_name='fightercareerstats',
            name='ko_tko',
        ),
        migrations.RemoveField(
            model_name='fightercareerstats',
            name='majority_decisions',
        ),
        migrations.RemoveField(
            model_name='fightercareerstats',
            name='split_decisions',
        ),
        migrations.RemoveField(
            model_name='fightercareerstats',
            name='submissions',
        ),
        migrations.RemoveField(
            model_name='fightercareerstats',
            name='tko_doctor_stoppages',
        ),
        migrations.RemoveField(
            model_name='fightercareerstats',
            name='unanimous_decisions',
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='dq_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='dq_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='ko_tko_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='ko_tko_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='majority_decision_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='majority_decision_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='split_decision_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='split_decision_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='submission_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='submission_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='tko_doctor_stoppage_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='tko_doctor_stoppage_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='unanimous_decision_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='unanimous_decision_wins',
            field=models.IntegerField(default=0),
        ),
    ]
