# Generated by Django 5.2.7 on 2025-12-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0018_remove_fightercareerstats_dq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightercareerstats',
            name='could_not_continue',
            field=models.IntegerField(default=0),
        ),
    ]
