# Generated by Django 5.2.7 on 2025-12-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0019_fightercareerstats_could_not_continue'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightercareerstats',
            name='total_fight_time',
            field=models.IntegerField(default=0),
        ),
    ]
