# Generated by Django 5.2.7 on 2025-12-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0020_fightercareerstats_total_fight_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightercareerstats',
            name='could_not_continue',
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='ctrl_time_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='sig_str_attempted_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='sig_str_landed_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='tas_attempted_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='ts_landed_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='ctrl_time_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='sig_str_attempted_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='sig_str_landed_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='tas_attempted_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='ts_landed_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
