# Generated by Django 5.2.7 on 2025-12-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0021_remove_fightercareerstats_could_not_continue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightercareerstats',
            name='tas_attempted_opp',
        ),
        migrations.RemoveField(
            model_name='fightercareerstats',
            name='ts_landed_opp',
        ),
        migrations.RemoveField(
            model_name='fightstats',
            name='tas_attempted_opp',
        ),
        migrations.RemoveField(
            model_name='fightstats',
            name='ts_landed_opp',
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='td_attempted_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fightercareerstats',
            name='td_landed_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='td_attempted_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fightstats',
            name='td_landed_opp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
