# Generated by Django 5.2.7 on 2025-12-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0022_remove_fightercareerstats_tas_attempted_opp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighters',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
