# Generated by Django 5.2.7 on 2026-01-24 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0023_fighters_normalized_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('SETUP', 'Setup'), ('DRAFTING', 'Drafting'), ('LIVE', 'Live'), ('COMPLETED', 'Completed')], default='SETUP')),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('join_key', models.CharField(max_length=12, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_SCHEDULED', 'Not Scheduled'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_SCHEDULED', max_length=16)),
                ('draft_date', models.DateTimeField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.league')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CREATOR', 'Creator'), ('PLAYER', 'Player')], default='PLAYER')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.league')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.leaguemember')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('STRAWWEIGHT', 'Strawweight'), ('FLYWEIGHT', 'Flyweight'), ('BANTAMWEIGHT', 'Bantamweight'), ('FEATHERWEIGHT', 'Featherweight'), ('LIGHTWEIGHT', 'Lightweight'), ('WELTERWEIGHT', 'Welterweight'), ('MIDDLEWEIGHT', 'Middleweight'), ('LIGHT_HEAVYWEIGHT', 'Light Heavyweight'), ('HEAVYWEIGHT', 'Heavyweight'), ('FLEX', 'Flex')], max_length=32)),
                ('fighter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.fighters')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.team')),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_num', models.IntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.draft')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.fighters')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fighter', 'draft'), name='unique_fighter_in__draft'), models.UniqueConstraint(fields=('pick_num', 'draft'), name='unique_pick_num_in_draft')],
            },
        ),
        migrations.CreateModel(
            name='DraftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_num', models.IntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.draft')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.team')),
            ],
            options={
                'ordering': ['pick_num'],
                'constraints': [models.UniqueConstraint(fields=('draft', 'pick_num'), name='unique_draft_pick_in_draft')],
            },
        ),
    ]
