# Generated by Django 5.2.7 on 2026-02-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0024_league_draft_leaguemember_team_roster_draftpick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='current_pick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draft',
            name='pick_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
