# Generated by Django 5.2.7 on 2026-02-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0025_draft_current_pick_draft_pick_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='slot_type',
            field=models.CharField(choices=[('SW', 'Strawweight'), ('FLW', 'Flyweight'), ('BW', 'Bantamweight'), ('FW', 'Featherweight'), ('LW', 'Lightweight'), ('WW', 'Welterweight'), ('MW', 'Middleweight'), ('LHW', 'Light Heavyweight'), ('HW', 'Heavyweight'), ('FLEX', 'Flex')], max_length=32),
        ),
    ]
