# Generated by Django 5.2.7 on 2026-02-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0026_alter_roster_slot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighters',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
