# Generated by Django 5.2.7 on 2026-03-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0027_fighters_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighters',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fighters',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='fighters',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'dob'), name='unique_fighter'),
        ),
    ]
