# Generated by Django 5.2.7 on 2026-03-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0028_alter_fighters_full_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='events',
            constraint=models.UniqueConstraint(fields=('event', 'date'), name='unique_event'),
        ),
    ]
