# Generated by Django 5.2.7 on 2026-04-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0029_events_unique_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
