# Generated by Django 5.2.7 on 2026-04-07 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0031_scoringrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAppliedFightScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('fight_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.fightscore')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'fight_score'), name='unique_team_fight_score_application')],
            },
        ),
    ]
