# Generated by Django 5.2.7 on 2026-04-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0032_teamappliedfightscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
