# Generated by Django 5.2.7 on 2026-04-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0033_team_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighters',
            name='img_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
