# Generated by Django 5.2.7 on 2026-04-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0033_team_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
