# Generated by Django 5.2.7 on 2026-05-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0034_fighters_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
